python_exceptions = [
    "SyntaxError",
    "NameError",
]

my_exception = python_exceptions[2]